version: "3"

services:
  web:
    build:
      context: .
      args:
        GITLAB_PACKAGES_TOKEN: ${GITLAB_PACKAGES_TOKEN}
    command: sh -c "python manage.py migrate && python manage.py runserver 0:8000" 
    volumes:
      - .:/project
    ports:
      - ${WEB_PORT:-8000}:8000
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
