# Generated by Django 4.1.7 on 2023-05-04 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("page", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.RemoveField(
            model_name="applicationpageapplicationplacement",
            name="application",
        ),
        migrations.RemoveField(
            model_name="applicationpageapplicationplacement",
            name="page",
        ),
        migrations.AlterModelOptions(
            name="applicationpage",
            options={},
        ),
        migrations.RemoveField(
            model_name="applicationpage",
            name="logo",
        ),
        migrations.AddField(
            model_name="applicationpage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="applicationpage",
            name="name",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name="Application",
        ),
        migrations.DeleteModel(
            name="ApplicationPageApplicationPlacement",
        ),
    ]
