# Generated by Django 4.1.7 on 2023-04-18 15:31

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("home", "0004_alter_homepage_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DigitalisationPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("introduction", models.CharField(max_length=255, null=True)),
                ("desc_of_digital_section", wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                "verbose_name": "Home Page",
            },
            bases=("wagtailcore.page",),
        ),
    ]
