# Generated by Django 4.1.7 on 2023-04-20 12:23

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("home", "0007_contactpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="digitalisationpage",
            name="app_desc",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="digitalisationpage",
            name="app_intro",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="digitalisationpage",
            name="app_title",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="digitalisationpage",
            name="cloud_desc",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="digitalisationpage",
            name="cloud_intro",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="digitalisationpage",
            name="cloud_left_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Choisir votre contact image",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="digitalisationpage",
            name="cloud_right_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Choisir votre contact image",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="digitalisationpage",
            name="cloud_second_right_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Choisir votre contact image",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="digitalisationpage",
            name="cloud_title",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="digitalisationpage",
            name="digital_approch_title",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="digitalisationpage",
            name="digital_revolution_title",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="digitalisationpage",
            name="digital_transition_title",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="missionpage",
            name="global_approch_desc",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="missionpage",
            name="global_approch_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Choisir votre contact image",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="missionpage",
            name="global_approch_intro",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="missionpage",
            name="global_approch_small_text",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="missionpage",
            name="global_approch_title",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="missionpage",
            name="innovation_approch_desc",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="missionpage",
            name="innovation_approch_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Choisir votre contact image",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="missionpage",
            name="innovation_approch_intro",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="missionpage",
            name="innovation_approch_small_text",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="missionpage",
            name="innovation_approch_title",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="missionpage",
            name="transition_approch_desc",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="missionpage",
            name="transition_approch_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Choisir votre contact image",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="missionpage",
            name="transition_approch_intro",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="missionpage",
            name="transition_approch_small_text",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="missionpage",
            name="transition_approch_title",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
