# Generated by Django 4.1.7 on 2023-04-27 10:53

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("home", "0015_projectpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="digitalisationpage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="Choisir votre image",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="home",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="homepagehomeplacement",
            name="home",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="home.home",
            ),
        ),
        migrations.AlterField(
            model_name="homepagehomeplacement",
            name="page",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="home_placements",
                to="home.homepage",
            ),
        ),
    ]
