# Generated by Django 4.1.7 on 2023-04-27 11:18

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_alter_digitalisationpage_image_alter_home_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactpage",
            name="message",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="digitalisationpage",
            name="description",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Entrer votre description", null=True
            ),
        ),
        migrations.AlterField(
            model_name="missionpage",
            name="second_desc",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Entrer votre seconde description", null=True
            ),
        ),
    ]
