# Generated by Django 4.1.7 on 2023-04-27 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_alter_contactpage_message_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisionPage",
            fields=[
                (
                    "digitalisationpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.digitalisationpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vision Page",
            },
            bases=("home.digitalisationpage",),
        ),
        migrations.AlterField(
            model_name="digitalisationpage",
            name="introduction",
            field=models.CharField(
                blank=True,
                help_text="Entrer votre introduction",
                max_length=255,
                null=True,
            ),
        ),
    ]
