# Generated by Django 4.1.7 on 2023-04-28 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("home", "0019_homepage_home_commitment_logo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="home_commitment_logo",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="home_mission_logo",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="home_novelty_logo",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="home_project_logo",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="home_vision_logo",
        ),
        migrations.AddField(
            model_name="digitalisationpage",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
