# Generated by Django 4.1.7 on 2023-05-08 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0024_homepage_youtube"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homepage",
            old_name="youtube",
            new_name="youtube_url",
        ),
    ]
