# Generated by Django 4.1.9 on 2023-05-23 13:29

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('home', '0026_homepage_slogan_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trusts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
        ),
        migrations.RemoveField(
            model_name='digitalisationpage',
            name='logo',
        ),
        migrations.CreateModel(
            name='TrustsPageTrustsPlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trusts_items', to='home.homepage')),
                ('trusts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.trusts')),
            ],
            options={
                'verbose_name': 'trusts placement',
                'verbose_name_plural': 'trusts placements',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
