# Generated by Django 4.1.9 on 2023-05-23 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('home', '0027_trusts_remove_digitalisationpage_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalisationpage',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
