# Generated by Django 4.1.9 on 2023-05-23 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_digitalisationpage_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalisationpage',
            name='logo',
        ),
    ]
