# Generated by Django 4.1.9 on 2023-05-24 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_remove_homepage_home_image_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='home_desc_novelty',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='home_desc_project',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='home_image_novelty',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='home_title_novelty',
        ),
    ]
