# Generated by Django 4.1.9 on 2023-05-31 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_contactpage_missionpage_visionpage_projectpage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactPage',
        ),
    ]
