# Generated by Django 4.1.9 on 2023-06-01 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_delete_contactpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='home_description',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='home_image_logo',
        ),
    ]
