# Generated by Django 4.1.9 on 2023-06-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_remove_homepage_home_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionpagerelateditemforhome',
            name='icon',
            field=models.CharField(help_text="Donner la class de l'icon ", max_length=255, null=True),
        ),
    ]
