# Generated by Django 4.1.9 on 2023-06-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_alter_missionpagerelateditemforhome_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionpagerelateditem',
            name='icon',
            field=models.CharField(help_text="Donner la class de l'icon ", max_length=255, null=True),
        ),
    ]
