# Generated by Django 4.1.7 on 2023-05-05 15:27

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0002_remove_headersettings_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="headersettings",
            name="slideshow",
            field=wagtail.fields.StreamField(
                [("description", wagtail.blocks.RichTextBlock())],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
