# Generated by Django 4.1.7 on 2023-05-08 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0003_headersettings_slideshow"),
    ]

    operations = [
        migrations.RenameField(
            model_name="headersettings",
            old_name="slideshow",
            new_name="carousel_item",
        ),
    ]
