# Generated by Django 4.1.7 on 2023-05-08 16:05

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0004_rename_slideshow_headersettings_carousel_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="headersettings",
            name="carousel_item",
            field=wagtail.fields.StreamField(
                [
                    (
                        "slide",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "description",
                                    wagtail.blocks.RichTextBlock(
                                        features=["bold", "italic"]
                                    ),
                                ),
                                (
                                    "page",
                                    wagtail.blocks.PageChooserBlock(required=False),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
