# Generated by Django 4.1.9 on 2023-05-23 10:41

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0007_remove_headersettings_page_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headersettings',
            name='page_item',
            field=wagtail.fields.StreamField([('slide', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(required=False))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
