# Generated by Django 4.1.7 on 2023-04-18 16:59

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("home", "0006_missionpage_alter_digitalisationpage_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactPage",
            fields=[
                (
                    "digitalisationpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.digitalisationpage",
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                (
                    "email",
                    models.EmailField(
                        default="contact@newrai.fr", max_length=255, null=True
                    ),
                ),
                ("object", models.CharField(max_length=255, null=True)),
                ("message", wagtail.fields.RichTextField()),
                (
                    "conatct_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Choisir votre contact image",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Page",
            },
            bases=("home.digitalisationpage",),
        ),
    ]
