# Generated by Django 4.1.7 on 2023-04-25 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_home_homepage_home_image_logo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offers",
            fields=[
                (
                    "home_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.home",
                    ),
                ),
                ("icon_class", models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=("home.home",),
        ),
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "offers_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.offers",
                    ),
                ),
            ],
            bases=("home.offers",),
        ),
    ]
