# Generated by Django 4.1.7 on 2023-04-26 15:49

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_remove_offers_home_ptr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="home_title_commitment",
            field=models.CharField(
                blank=True,
                help_text="Ajouter le titre d'engagement",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="home_title_novelty",
            field=models.CharField(
                blank=True,
                help_text="Ajouter le titre de noveauté",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="home_title_project",
            field=models.CharField(
                blank=True,
                help_text="Ajouter le titre du projet",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contactpage",
            name="message",
            field=wagtail.fields.RichTextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="contactpage",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="digitalisationpage",
            name="app_desc",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="digitalisationpage",
            name="cloud_desc",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="digitalisationpage",
            name="desc_of_digital_section",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="digitalisationpage",
            name="first_intro_mission",
            field=models.CharField(
                blank=True,
                help_text="1ère introduction de l'offre",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="first_intro_mission",
            field=models.CharField(
                blank=True,
                help_text="Ajouter la 1ére introduction de mission",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="home_intro_vision",
            field=models.CharField(
                blank=True,
                help_text="Ajouter l'introduction de vision",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="home_title_vision",
            field=models.CharField(
                blank=True,
                help_text="Ajouter le titre de vision",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="second_intro_mission",
            field=models.CharField(
                blank=True,
                help_text="Ajouter la 2ème introduction de mission",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="missionpage",
            name="global_approch_desc",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="missionpage",
            name="innovation_approch_desc",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="missionpage",
            name="transition_approch_desc",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
