# Generated by Django 4.1.7 on 2023-05-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0022_homepage_slogan_description_homepage_slogan_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactpage",
            name="entreprise",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="fonction",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
