# Generated by Django 4.1.7 on 2023-05-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0023_contactpage_entreprise_contactpage_fonction"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="youtube",
            field=models.URLField(
                blank=True,
                help_text="Your YouTube channel or user account URL",
                null=True,
            ),
        ),
    ]
