# Generated by Django 4.1.7 on 2023-05-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0003_alter_applicationpage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationpage",
            name="youtube_url",
            field=models.URLField(
                blank=True,
                help_text="Your YouTube channel or user account URL",
                null=True,
            ),
        ),
    ]
