# Generated by Django 4.1.7 on 2023-05-08 16:13

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0005_alter_headersettings_carousel_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="headersettings",
            name="page_item",
            field=wagtail.fields.StreamField(
                [
                    (
                        "slide",
                        wagtail.blocks.StructBlock(
                            [("page", wagtail.blocks.PageChooserBlock(required=False))]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="headersettings",
            name="carousel_item",
            field=wagtail.fields.StreamField(
                [("description", wagtail.blocks.RichTextBlock())],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
